[package]

name = "linear-map"
version = "0.0.1"
license = "MIT/Apache-2.0"
description = "A map backed by a vector"
authors = [
    "Alexis Beingessner <a.beingessner@gmail.com>",
]

repository = "https://github.com/contain-rs/linear-map"
documentation = "https://contain-rs.github.io/linear-map/linear-map"
keywords = ["data-structures"]
readme = "README.md"
